export const PATHS = {
  github: 'https://github.com/patrickgdl',
  twitter: 'https://twitter.com/opatrickgdl',
  linkedin: 'https://www.linkedin.com/in/patrickgdl/',
  picpayURL: 'https://www.picpay.com.br/',
  c6bankURL: 'https://www.c6bank.com.br/',
  email: 'mailto:patrickgdlima@gmail.com',
  base: process.env.NEXT_PUBLIC_URL,
  home: '/',
  about: '/about',
  writing: '/writing',
  now: '/now',
  work: '/work',
  madeiramadeira: '/work/madeiramadeira',
  madeiramadeiraURL: 'https://madeiramadeira.com.br/',
  picpay: '/work/picpay',
  picpayWorkURL: 'https://lojista.picpay.com/registro/',
  portfolioV1: '/work/portfolio-v1',
  portfolioV1URL: 'https://v1.patricklima.dev',
  writings: './src/data/writings',
  data: './src/data/',
} as const;
